model_params:
  name: 'VQVAE'
  in_channels: 1
  embedding_dim: 64
  num_embeddings: 512
  beta: 0.25
  img_size: 128

exp_params:
  dataset: screentone
  data_path: "../../../shared/datasets/real_screentone"
  img_size: 128
  batch_size: 144 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 80

logging_params:
  save_dir: "logs/"
  name: "Screentone-VQVAE"
  manual_seed: 1265
